# Site information
site_name: MCW Research Computing
site_description: A site for documenting MCW Research Computing systems and services.
site_author: MCW RCC
site_url: https://docs.rcc.mcw.edu
repo_url: https://github.com/mcw-rcc/mcw-rcc.github.io/
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/bookshelf
    admonition:
      tip: material/lightbulb-outline
  custom_dir: overrides

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

# Custom
extra:
  support_email: <help-rcc@mcw.edu>
  hpc_name: HPC
  analytics:
    provider: google
    property: !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mcw-rcc

# CSS
extra_css:
  - stylesheets/extra.css
  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Plugins
plugins:
  - macros
  - search
  - glightbox:
      closeOnOutsideClick: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

# Page tree
nav:
  - Home:
    - Overview: index.md
    - Recent News: news.md
    - Grant Boilerplate: grants.md
    - Publications: pubs.md
    - FAQ: faq.md
  - User Guide: 
    - Quick Start: user-guide/quickstart.md
    - Getting an Account: user-guide/accounts.md
    - User Etiquette: user-guide/etiquette.md
    - Connecting:
      - Logging in: user-guide/access/login.md
      - Open OnDemand: user-guide/access/ondemand.md
      - SSH Connection: user-guide/access/ssh.md
      - Remote Access: user-guide/access/remote-access.md
    - Running Jobs: 
      - Submitting SLURM Jobs: user-guide/jobs/running-jobs.md
      - Staging Data: user-guide/jobs/storage-job.md
      - Software in a Job: user-guide/jobs/software-job.md 
      - Troubleshoot Jobs: user-guide/jobs/troubleshoot.md
      - Job Metrics: user-guide/jobs/xdmod.md
  - Data Storage:
    - storage/rcc-storage.md
    - storage/paid-storage.md 
    - storage/ref-data.md
    - storage/mcw-storage.md
    - Access & Sharing:
      - storage/data-access.md
      - storage/data-sharing.md
    - Manage:
      - storage/file-cleanup.md
      - storage/file-recovery.md
      - storage/file-transfer.md
      - storage/file-permissions.md
  - Software:
    - Using Modules: software/modules.md
    - Requesting Software: software/module-request.md
    - Guides:
      - software/alphafold.md
      - software/ansys.md
      - software/lsdyna.md
      - software/matlab.md
      - software/python.md
      - software/pytorch.md
      - software/R.md 
      - software/schrodinger.md
      - software/singularity.md
      - software/tensorflow.md      
  - ResHPC:
    - Overview: secure-computing/reshpc.md
    - Accounts & Projects: secure-computing/project-account.md
    - Logging in: secure-computing/mfa-login.md
    - Storage: secure-computing/project-storage.md
    - Run a Job: secure-computing/workflow.md
    - Software: secure-computing/software.md
