# Site information
site_name: MCW Research Computing
site_description: A site for documenting MCW Research Computing systems and services.
site_author: MCW RCC
site_url: https://docs.rcc.mcw.edu
repo_url: https://github.com/mcw-rcc/mcw-rcc.github.io/
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/bookshelf
    admonition:
      tip: material/lightbulb-outline
  custom_dir: overrides

  features:
  #  - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy

# Custom
extra:
  support_email: <help-rcc@mcw.edu>
  hpc_name: HPC
  analytics:
    provider: google
    property: G-50ZTKYWP10
  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mcw-rcc

# CSS
extra_css:
  - _static/css/extra.css
  
extra_javascript:
  - _static/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Plugins
plugins:
  - search
  - glightbox
  - blog:
      post_date_format: medium
      pagination_per_page: 5 
      blog_dir: news
      archive: false
      categories: false
  - rss:
      match_path: news/posts/.*
      date_from_meta:
        as_creation: date
  - git-revision-date-localized
  - macros:
      include_yaml:
        - includes/modules.yml
        - includes/r-packages.yml
  - table-reader
  - redirects:
      redirect_maps:
        'user-guide/quickstart.md': 'cluster/quickstart.md'
        'user-guide/accounts.md': 'cluster/accounts.md'
        'user-guide/etiquette.md': 'cluster/etiquette.md'
        'user-guide/hardware.md': 'cluster/hardware.md'
        'user-guide/access/login.md': 'cluster/access/login.md'
        'user-guide/access/ondemand.md': 'cluster/access/ondemand.md'
        'user-guide/access/remote-access.md': 'cluster/access/remote-access.md'
        'user-guide/access/mobaxterm.md': 'cluster/access/mobaxterm.md'
        'user-guide/access/putty.md': 'cluster/access/putty.md'
        'user-guide/access/ssh-keys.md': 'cluster/access/ssh-keys.md'
        'user-guide/jobs/running-jobs.md': 'cluster/jobs/running-jobs.md'
        'user-guide/jobs/storage-job.md': 'cluster/jobs/storage-job.md'
        'user-guide/jobs/software-job.md': 'cluster/jobs/software-job.md'
        'user-guide/jobs/troubleshoot.md': 'cluster/jobs/troubleshoot.md'
        'user-guide/jobs/xdmod.md': 'cluster/jobs/xdmod.md'

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - footnotes

# Page tree
nav:
  - Home:
    - Overview: index.md
    - Recent News: news/index.md
    - Grant Boilerplate: grants.md
    - Publications: pubs.md
    - Maintenance: maintenance.md
    - FAQ: faq.md
  - Cluster: 
    - Quick Start: cluster/quickstart.md
    - Getting an Account: cluster/accounts.md
    - User Etiquette: cluster/etiquette.md
    - Hardware Specs: cluster/hardware.md
    - Connecting:
      - Logging in: cluster/access/login.md
      - Open OnDemand: cluster/access/ondemand.md
      - Remote Access: cluster/access/remote-access.md
      - SSH Clients:
        - MobaXterm: cluster/access/mobaxterm.md
        - PuTTY: cluster/access/putty.md
      - SSH Keys: cluster/access/ssh-keys.md
    - Running Jobs: 
      - Submitting SLURM Jobs: cluster/jobs/running-jobs.md
      - Using Data in a Job: cluster/jobs/storage-job.md
      - Software in a Job: cluster/jobs/software-job.md 
      - Troubleshoot Jobs: cluster/jobs/troubleshoot.md
      - Job Metrics: cluster/jobs/xdmod.md
  - Data Storage:
    - storage/rcc-storage.md
    - storage/paid-storage.md 
    - storage/ref-data.md
    - storage/mcw-storage.md
    - Data Transfer:
      - storage/file-transfer.md
      - storage/globus.md
      - storage/rclone.md
    - Manage & Share:
      - storage/data-access.md
      - storage/data-sharing.md
      - storage/file-cleanup.md
      - storage/file-recovery.md
      - storage/file-permissions.md
  - Software:
    - Using Modules: software/modules.md
    - Requesting Software: software/module-request.md
    - Installed Software:
      - Cluster Packages: software/cluster-pkg-list.md
      - R Packages: software/r-pkg-list.md
    - Guides:
      - software/alphafold.md
      - software/ansys.md
      - software/conda.md
      - software/containers.md
      - software/git.md
      - software/advanced_git.md
      - software/jupyter.md
      - software/lsdyna.md
      - software/matlab.md
      - software/namd.md
      - software/nextflow.md
      - software/python.md
      - software/pytorch.md
      - software/R.md
      - software/schrodinger.md
      - software/tensorflow.md
  - ResHPC:
    - Overview: secure-computing/reshpc.md
    - Accounts & Projects: secure-computing/project-account.md
    - Storage: secure-computing/project-storage.md
    - Logging in: secure-computing/mfa-login.md
    - Data Transfer: secure-computing/mfa-data-transfer.md
    - Run a Job: secure-computing/workflow.md
    - Software: secure-computing/software.md
  - Learning:
    - Overview: learning/learning.md
    - HPC Clusters Tutorials: learning/hpc_clusters.md
    - SLURM Guides: learning/slurm.md
    - Programming Guides: learning/programming.md
